### ISSUE TITLE
Provide mechanism to prevent scopeless tests from executing

### ISSUE THREAD

**Issue by b00lduck** [mkutz/spock-scope-extension#2]
Introduce a parameter (e.g. spock.excludeScopeless or includeScopeless) to en/disable the execution of scopeless test cases.

Further the default case has to be defined.

**Comment by mkutz** [comment]
Nice Idea.

`excludeScopesless` is hard, since the extension is only called for Specifications and features which are annotated with `@Scope`. I would need convert it into a [global extension](https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/org/spockframework/runtime/extension/AbstractGlobalExtension.java) instead of a [annotation driven one](https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/org/spockframework/runtime/extension/AbstractAnnotationDrivenExtension.java). So not impossible, but hard.

`includeScopeless` does not make any sense to me for this is the current behavior.

**Comment by mkutz** [comment]
I think I implemented it:
- unscoped specs with only unscoped features will be ignored
- scoped features in unscoped specs will be executed

If neither includeScopes, nor excludeScopes is set, all scope annotations are ignored as in 0.3.

**Comment by mkutz** [comment]
I think I implemented the feature:
- If a spec and all its features are not scoped, it will be ignored in any scoped execution
- If a spec is

**Comment by mkutz** [comment]
Implemented on current master.
